language: node_js
node_js:
- '6'
- '5'
script:
- grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: 'fIaNCI615/U9ZkEubXN9VIo6PTZ5hRtyxYVlt5AnIBrVlOFUjaXpvVpic7TtNIKMtcPN6tHCB6AO+ameMZZmQ/gTzehYq6Y/xi8MY3PgJp/Hf87RmW8FuWXC8Zqjakfu6CsmSax8X4IydWf30sls69LGy/BKe6TSYXy7SMnnQlvBBBvX8HBw0NuVzqmJmRTbq+o3IZGEASiguGvHqBL/RA0C0E3+d24AefojVztMvd1SgEEtZ8s2x57SPfagtjiMIYfVZ/bNy5LqJyjNMBE5vsMSBset3Ohtw3ASQKmzSej31PyVNHGiN9AhSDNkiUtJGVXeSCWqLSjXtdnWGly/77hGtpBmOp0CGnkPzWhTnGTAfEirjteQnUOeMwTTTu+nIzdgnO6hucfG/ez4nWhD89VMQLW7wkR+hJtSHSLV7vsRqHUT+cgSyR7aL1QPMaJGg1LOpyRaOywSb0X+QbYS4hFPMgepGg2SO1G9bYan5ESFnJN0FBiUAReK67wficOAkemCzYFhqVZannk7zfOzwgCOlmR6Yb/6Vjvs+5YOk5ODQCtt4Q7ypUZekWulU26nhYGNqgjoCikHbGab2SU4RWRAFCj/ECZooiafOgDsCunzZBDPK0PslBWVDTpgX1On3aqr9rHRGAjjhLocKPwcc1TDpNe62c1P5LU7uMnE0Fw='
  on:
    tags: true
    branch: master
    node: '5'
    repo: Cimpress-MCP/request-middleware-framework
