language: node_js
node_js:
- '6'
- '5'
script:
- grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: GYRflwfMTaQ2uAq8zumRy297cID8kxGwcr7mbDaq7vBuzDn0Co4Mx0UNuEJqy+2yf5qS2BTEfbShSblSjEJNK0e4JgfUukKewW6hBXxKwROsSRHC+xv9onbGwA6ecPD4+wMFcB+ceTf9dqyGl1iaaK2sH5uvZkFBQ8AgviLH1B28SCIkOMFHBt5Ke41iVHMtv9IoK3rKBWWwFWB1COuUM/yKYZGXIrr5ONP+RqudXQRCHXk+GoJdp9PqXNdK0gP/hP5HRhoFH2CU3mRjVCfYM6s2Cg6r8B5IFAFqfUrnofQm6bL2UBj7N9KAxknpaPoPT8D03CGw2JEl/UX5tCu/fZKXOJuGfO5rwEtB+EZh1epxAMLJPRg98DUj38zKCe5nNsNZLrn+VaesNqEJemz1zVIZxR+Jf+7bmKExlBn2wUTG9v9L2oPF9wRa+dc+z4lJAMFKIhm5UfIkhHodS9XYztL4BzQaziJyc7tEK0gBjNAR2QYgMo8HKG3pldJsKwGeR1MjxRsNFO2ANAVihVBHqeeZdaYJ2VY3FJwYD6FjR4HQwrl4De9o8AWToLsjFJ4ZXj6nbkV2cBna5bDf9UG82x2wR0JK9BWXPYxIxQjazx9DOcZhPMm1RXEFRiF+b95hAgwczthzGOjUc+dtrT+aCuNSDRobjz3Q7cz3HFfsrXQ=
  on:
    tags: true
    branch: master
    node: '5'
    repo: Cimpress-MCP/request-middleware-framework
